[package]
name = "reduce"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Fold an iterator without an initial value"
repository = "https://github.com/dtolnay/reduce"
documentation = "https://github.com/dtolnay/reduce"
keywords = ["iterator", "fold"]
